### ISSUE TITLE
Provide more descriptive functions

### ISSUE THREAD

**Issue by schwern** [pdl/Test-Proto#23]
p, pOb, pAr... I can sort of work out what they mean, but they're mostly difficult to understand and an immediate visual turn off to what is a great idea.

It seems silly to have a three letter function name when you're going to follow it with chained method calls like `is_like(qr{ some long regex })`.  The utility of this module is not in short names, but in building up a test case through declarations.  That's the cognitive, code and space saving.  Focus on that.

One can go and use the full object constructor, `Test::Proto::Object->new`, but that's now far too much.  There needs to be a middle ground.

I'd encourage you to provide more descriptive functions.  `proto`, `proto_Object`, `proto_Array`.  Even `p`, `pObject` and `pArray`.

**Comment by pdl** [comment]
Thank for the feedback!

I made it short because when I'm using it I tend to start with a structure I can get it to dwim, something like: `pHr({a=>qr/^[a-z]/})` (I think I implemented that already...). Equally, though, I think you're right, it's a bit cryptic, and full names would help readability.
