### ISSUE TITLE
Use subtests

### ISSUE THREAD

**Issue by schwern** [pdl/Test-Proto#29]
This would all be a whole lot simpler if each call to `ok` ran all the tests as a subtest.

Right now, a Test::Proto test produces a single ok line.  This isn't a very good indication of what's really going on.  It also goes to some lengths to implement existing Test::More and Test::Builder functions itself so they only fail.  Finally, only the _first_ test fails which doesn't give the full story for debugging.

If `ok` ran `validate` in a subtest, then each test method (is_like and so on) can run as a normal test, succeeding or failing.  The normal Test::More and Test::Builder calls can be used.  And all test output and failures can be displayed.

**Comment by pdl** [comment]
I agree. It is issue #1 - I'm just getting there slowly so the work isn't in the master branch at the moment, nor applied to most of the prototype classes.

**Comment by pdl** [comment]
Closed as duplicate.
